version: "3.8"

services:
  app:
    image: ghcr.io/fedroaja/basic-cicd:latest
    container_name: express-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always