name: CI/CD Pipeline

on:
  push:
    branches:
      - development
      - staging
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/fedroaja/basic-cicd

jobs:
  build-test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        shell: powershell
        run: |
          docker logout ghcr.io
          docker login ghcr.io -u fedroaja -p "${{ secrets.GHCR_PAT }}"

      - name: Build image
        shell: powershell
        run: |
          docker build -t $env:IMAGE_NAME:temp .

      - name: Run tests
        shell: powershell
        run: |
          docker run --rm $env:IMAGE_NAME:temp npm test

  # -------------------------
  # STAGING DEPLOY (branch)
  # -------------------------
  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: self-hosted
    needs: build-test

    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        shell: powershell
        run: |
          docker login ghcr.io -u fedroaja -p "${{ secrets.GHCR_PAT }}"

      - name: Build & Push staging image
        shell: powershell
        run: |
          $tag = "$env:IMAGE_NAME:staging"

          docker build -t $tag .
          docker push $tag

      - name: Backup current version
        shell: powershell
        run: |
          docker tag $env:IMAGE_NAME:staging $env:IMAGE_NAME:staging-backup
          docker push $env:IMAGE_NAME:staging-backup

      - name: Deploy staging
        shell: powershell
        run: |
          $env:IMAGE = "$env:IMAGE_NAME:staging"
          docker compose up -d --force-recreate

  # -------------------------
  # PRODUCTION DEPLOY (tag)
  # -------------------------
  deploy-production:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: self-hosted
    needs: build-test

    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        shell: powershell
        run: |
          docker login ghcr.io -u fedroaja -p "${{ secrets.GHCR_PAT }}"

      - name: Set version
        id: version
        shell: powershell
        run: |
          $version = "${{ github.ref_name }}"
          echo "VERSION=$version" >> $env:GITHUB_ENV

      - name: Backup current production
        shell: powershell
        run: |
          docker pull $env:IMAGE_NAME:latest
          docker tag $env:IMAGE_NAME:latest $env:IMAGE_NAME:rollback
          docker push $env:IMAGE_NAME:rollback

      - name: Build & Push versioned image
        shell: powershell
        run: |
          docker build -t $env:IMAGE_NAME:$env:VERSION .
          docker tag $env:IMAGE_NAME:$env:VERSION $env:IMAGE_NAME:latest

          docker push $env:IMAGE_NAME:$env:VERSION
          docker push $env:IMAGE_NAME:latest

      - name: Deploy production
        shell: powershell
        run: |
          $env:IMAGE = "$env:IMAGE_NAME:latest"
          docker compose up -d --force-recreate