name: CI/CD Pipeline

on:
  push:
    branches:
      - development
      - staging
      - main

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: self-hosted
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: fedroaja/basic-cicd

    steps:
      - uses: actions/checkout@v4

      - name: Debug env
        shell: powershell
        run: |
          Write-Host "REGISTRY = $env:REGISTRY"
          Write-Host "IMAGE_NAME = $env:IMAGE_NAME"

      - name: Check token length
        shell: powershell
        run: |
          $token = "${{ secrets.GHCR_PAT }}"
          Write-Host "Token length: $($token.Length)"

      - name: Login to GHCR
        shell: powershell
        run: |
          docker logout ghcr.io
          docker login ghcr.io -u fedroaja -p "${{ secrets.GHCR_PAT }}"

      - name: Build test image
        shell: powershell
        run: |
          docker build -t "$env:REGISTRY/$env:IMAGE_NAME:${{ github.sha }}" .

      - name: Run tests
        shell: powershell
        run: |
          docker run --rm "$env:REGISTRY/$env:IMAGE_NAME:${{ github.sha }}" npm test

  deploy:
    runs-on: self-hosted
    needs: test
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: fedroaja/basic-cicd

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        shell: powershell
        run: |
          docker logout ghcr.io
          docker login ghcr.io -u fedroaja -p "${{ secrets.GHCR_PAT }}"

      - name: Build & Push image
        shell: powershell
        run: |
          $tag = "$env:REGISTRY/$env:IMAGE_NAME:${{ github.sha }}"
          $latest = "$env:REGISTRY/$env:IMAGE_NAME:latest"

          docker build -t $tag .
          docker tag $tag $latest

          docker push $tag
          docker push $latest

      - name: Stop old containers
        shell: powershell
        run: |
          docker compose down --remove-orphans

      - name: Deploy development
        if: github.ref == 'refs/heads/development'
        shell: powershell
        run: |
          $env:IMAGE = "$env:REGISTRY/$env:IMAGE_NAME:${{ github.sha }}"
          docker compose up -d --force-recreate

      - name: Deploy staging
        if: github.ref == 'refs/heads/staging'
        shell: powershell
        run: |
          $env:IMAGE = "$env:REGISTRY/$env:IMAGE_NAME:${{ github.sha }}"
          docker compose up -d --force-recreate

      - name: Deploy production
        if: github.ref == 'refs/heads/main'
        shell: powershell
        run: |
          $env:IMAGE = "$env:REGISTRY/$env:IMAGE_NAME:${{ github.sha }}"
          docker compose up -d --force-recreate